consistent card heights obtained
openzim/kolibri pull request #121
Opened 2024-03-31 23:20 UTC by Sudarshan-21

2024-04-04 07:51 UTC, benoit74 commented
@Sudarshan-21 thank you! Once this PR is ready, please share here a screenshot of the before / after situation so that our PM can decide if this makes sense or not

2024-04-04 16:32 UTC, Sudarshan-21 commented
> @Sudarshan-21 thank you! Once this PR is ready, please share here a screenshot of the before / after situation so that our PM can decide if this makes sense or not

sure.

2024-04-08 08:43 UTC, benoit74 commented
@Popolechien do you prefer the UI "before" or "after" this change? 

The idea is that in some **rare** occasions (not encountered so far on real channels, only on test stuff where I merged content from multiple channels into a test channel), the topic image might not be always the same height, and it leads to a weird UI.

@Sudarshan-21 considers that current new UI ("before" screenshot above) is not adequate and is proposing to change it to the "after" UI where all cards have the same height.

Personally I tend to prefer the "before" UI because images are never distorted, while they are in the "after" situation (and cropping instead of distorting them would not help much since it would cut some text at a random position, since we have no control on where important content is placed in the image). I agree it is not perfect, but I have no clue about how to make it perfect without ensuring that images in the channel we use are always the same height for a given topic (which is most probably the case 99% of the time).

I'm quite sure that distorting images will cause more users to complain than having cards of various heights.

WDYT?

2024-04-08 09:14 UTC, Popolechien commented
> The idea is that in some rare occasions (not encountered so far on real channels

@benoit74 So basically implementing it is not likely to have any material effect on current display (except for rare and yet-unseen-in-the-wild-occasions), correct?

Regarding the distortion: how hard is it to set the default height to that of the tallest image, and for all other images adapt the text region to make up for it accordingly (which means that image height would not be hardcoded but relative to the available set)? 

In either case (distortion or not), having cards at the same height would be my preferred path going forward.

2024-04-08 09:32 UTC, benoit74 commented
> So basically implementing it is not likely to have any material effect on current display (except for rare and yet-unseen-in-the-wild-occasions), correct?

Correct

> Regarding the distortion: how hard is it to set the default height to that of the tallest image, and for all other images adapt the text region to make up for it accordingly (which means that image height would not be hardcoded but relative to the available set)?

@Sudarshan-21 could you please give it a try and share a screenshot? I like the idea, this is probably the best compromise to have no distortion but still consistent card height

> In either case (distortion or not), having cards at the same height would be my preferred path going forward.

Thank you!

2024-04-08 13:52 UTC, Sudarshan-21 commented
> If it is simple, please do so and share a screenshot. I don't think it is easy to understand your concern (which might be right) without a screenshot, at least I find it a bit vague

@benoit74 The following is the UI after the suggested improvisation 

![Screenshot from 2024-04-08 19-19-53](https://github.com/openzim/kolibri/assets/137636943/ebe3530b-637e-4e69-88d0-9e48b56b7ae6)

2024-04-08 13:58 UTC, benoit74 commented
@Popolechien does your thumb up means the last proposition is your preferred solution?

I like it indeed, I would just ensure there is some space between the text and the "Open" button in all circumstances (e.g. "Caperucita Roja" is a bit too close to "Open" button)

2024-04-08 14:14 UTC, Popolechien commented
Yep, looks good to me (and agree on the padding requirement)

2024-04-09 06:43 UTC, Sudarshan-21 commented
@benoit74 all of the required changes are made, you can review this PR

![Screenshot from 2024-04-09 12-07-55](https://github.com/openzim/kolibri/assets/137636943/20709663-118f-4c2c-91b8-c2bcbe5a1c4d)

2024-04-09 07:03 UTC, benoit74 requested changes
Your PR is not complete, you've made modifications only to the "default" cards, but not to "topic" and "more" cards, which have to be adapted as well to have consistent styling on all cards.

See conversations for additional details

2024-04-09 08:29 UTC, Sudarshan-21 commented on zimui/src/components/TopicHome.vue
> -          class="col-sm-6 col-md-6 col-lg-3 pt-3 pb-3"
Those paddings were within the card, having voids inside the div is unnecessary and the margin would serve the purpose of having space between cards.

2024-04-09 08:42 UTC, Sudarshan-21 commented on zimui/src/components/TopicHome.vue
> +        <footer class="mt-2 mb-1">
Having padding in the component is not needed. we just need to have some space between different elements which can be achieved by margin(which is a preferred way).

2024-04-09 08:47 UTC, Sudarshan-21 commented on zimui/src/components/TopicHome.vue
> +            class="w-100"
https://github.com/openzim/kolibri/issues/117#issuecomment-2025031828
the screenshot in this comment shows a card with reduced width, in order to fix the width the w-100 class is added.

2024-04-09 09:03 UTC, Sudarshan-21 commented on zimui/src/components/TopicCard.vue
> +.card-body{
This padding ensures the space between the title and the open button.

2024-04-09 09:06 UTC, Sudarshan-21 commented on zimui/src/components/TopicCard.vue
> +  width: 100%;
This is to ensure the image is not overflowing horizontally(I encountered that the last card image on the `minimal test` channel was horizontally overflowing)

2024-04-09 09:12 UTC, Sudarshan-21 commented on zimui/src/components/TopicCard.vue
> +    <a class="text-decoration-none text-reset h-100 " :href="`./files/${data.slug}`">
`h-100` removed from `<a>`
![Screenshot from 2024-04-09 14-38-47](https://github.com/openzim/kolibri/assets/137636943/6996f733-724d-42e3-85d1-da936677c147)

`h-100` removed from <div>
![Screenshot from 2024-04-09 14-39-06](https://github.com/openzim/kolibri/assets/137636943/1b867463-8565-4f46-a34f-6493d3926230)

removing any of them results in shrinked card size.

2024-04-09 15:39 UTC, Sudarshan-21 commented
> Your PR is not complete, you've made modifications only to the "default" cards, but not to "topic" and "more" cards, which have to be adapted as well to have consistent styling on all cards.

@benoit74 there were no styles given to the `topic` and `more` classes, so do we want all the styles of `card` classes to be applied to these two classes?

2024-04-11 07:34 UTC, benoit74 commented on zimui/src/components/TopicCard.vue
> +  width: 100%;
Got it, thank you

2024-04-11 07:35 UTC, benoit74 commented on zimui/src/components/TopicCard.vue
> +.card-body{
Got it, thank you

2024-04-11 07:35 UTC, benoit74 commented on zimui/src/components/TopicCard.vue
> +  overflow: hidden;
Got it, thank you

2024-04-11 07:35 UTC, benoit74 commented on zimui/src/components/TopicHome.vue
> +            class="w-100"
Got it, thank you

2024-04-11 07:41 UTC, benoit74 commented
> @benoit74 there were no styles given to the topic and more classes, so do we want all the styles of card classes to be applied to these two classes?

I'm not speaking about the `topic` and `more` classes, I'm speaking about the Vue/HTML code. Since for instance the "main" `div` all have at least the `card` class they inherit most of your changes but what is missing is other changes like the additional `h-100` and `open-badge` classes (btw, it shows that `open-badge` class should be renamed to something more generic since we want to apply this class to `topic` and `more` badges as well). Is it clearer?

2024-04-13 13:54 UTC, Sudarshan-21 commented
>all have at least the `card` class they inherit most of your changes but what is missing is other changes like the additional `h-100` 

I have moved the h-100 style to the card class itself. so this style will be applied whenever the card class is present.

>btw, it shows that `open-badge` class should be renamed to something more generic since we want to apply this class to `topic` and `more` badges as well)

I have renamed it, please check.
Is there anything more @benoit74?

2024-04-15 13:41 UTC, benoit74 requested changes
`badge-wrapper` class is still missing for "MORE" and "EXPLORE" buttons

2024-04-17 14:11 UTC, Sudarshan-21 commented
@benoit74 I have made the required changes, let me know if there are more things to be taken care of.

2024-04-18 08:16 UTC, benoit74 approved these changes
LGTM, works well when the 3 kind of cards are present now:

![image](https://github.com/openzim/kolibri/assets/7102089/05c51f31-7098-4adf-8944-9c4a964fb114)

Thank you!

2024-04-18 08:22 UTC, benoit74 commented
I just squashed all commits into one and enhanced the commit message

2024-04-18 08:23 UTC, merged